# Numpy and vectorization

In this lecture will be given a brief introduction to numpy and its uses in scientific computing.

In [1]:
import numpy as np #standard way of importing numpy library
import time #will be used later on

Numpy comes with numeric types, vectors, matrices (and their operations) extending the capabilities of base python computing. 

Vectors in general are ordered arrays of numbers; they are usually denoted with lower case bold letters, as $\mathbf{x}$. The elements of a vector are all of the same type and they cannot contain both numbers and characters; their dimension is identified by the number of elements present in the array (mathematically their dimension is also called rank). The elements of a vector can be referenced with an index and while mathematically these elements run from 1 to n, in computer science the elements usually run from 0 to n-1.

## Numpy arrays 

Above the dimension was the number of elements in the vector while here dimension refers to the number of indexes of an array. So for example, a one dimensional, or 1-D array, has one index.
Data creation routines in Numpy usually have a first parameter which is the shape of the object being defined; this can either be a single value, for a 1 dimensional array, or a tuple where we have to specify the shape of the array, like (n,m). Below there are some examples. 


In [2]:
#Numpy routines allocating memory and fill arrays with values

a = np.zeros(4)
b = np.zeros((4,))
print(a == b)
print(a)
print(f"np.zeros((4,)) produces: b = {b}, with shape {b.shape} and type {b.dtype}")
c = np.random.random_sample(4)
print(f"np.random.random_sample(4) produces: c = {c} with shape {c.shape} and type {c.dtype}")

[ True  True  True  True]
[0. 0. 0. 0.]
np.zeros((4,)) produces: b = [0. 0. 0. 0.], with shape (4,) and type float64
np.random.random_sample(4) produces: c = [0.62330553 0.4635631  0.48337888 0.36386885] with shape (4,) and type float64


In [3]:
d = np.arange(4.);              print(f"np.arange(4.):     d = {d}, a shape = {d.shape}, a data type = {d.dtype}")
e = np.random.rand(4);          print(f"np.random.rand(4): e = {e}, a shape = {e.shape}, a data type = {e.dtype}")

np.arange(4.):     d = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): e = [0.01700695 0.89277124 0.47692234 0.66155338], a shape = (4,), a data type = float64


In [4]:
#NumPy routines which allocate memory and fill with user specified values
f = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  f = {f},     a shape = {f.shape}, a data type = {f.dtype}")
g = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): g = {g}, a shape = {g.shape}, a data type = {g.dtype}")
h = np.array(["a", "b", "c"])
print(f"np.array(['a', 'b', 'c']) produces h = {h}, with shape {h.shape} and type {h.dtype}")

np.array([5,4,3,2]):  f = [5 4 3 2],     a shape = (4,), a data type = int32
np.array([5.,4,3,2]): g = [5. 4. 3. 2.], a shape = (4,), a data type = float64
np.array(['a', 'b', 'c']) produces h = ['a' 'b' 'c'], with shape (3,) and type <U1


These have all created a one-dimensional vector with four elements. The routine `.shape` returns the dimensions and here we can see that their shape is `(4,)` indicating a 1-d array with 4 elements.  

## Indexing and slicing

Elements of vectors can be accessed via indexing and slicing; numpy provides a complete set of indexing and slicing routines. In this context indexing means referring to an element of the array and referring it by its position in the array; slicing instead means getting a subset of elements from the vector. 


In [5]:
#vector indexing operations on one dimensional vectors
a = np.arange(10) #fill the vector a with numbers from 0 to 9
print(a)

#access an element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error; here the vector arrives at a[9]
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


In [14]:
#vector slicing operations work by using a set of three values (start:stop:step)
a = np.arange(10)
print(f"a = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c) #access elements from position 2 to position 7 in steps of 1

c = a[1:8:3]; print("a[1:8:3] = ", c)

b = np.array(['a', 'b', 'c'])
b_sliced = b[0:2:1]; print("slicing b this way [1:2:1] gives this ", b_sliced) #from here we can see that it halts the spot before the stop parameter

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c) #here the start is printed out

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c) #here again the stop is not printed out

# access all elements
c = a[:];         print("a[:]     = ", c) 

a = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[1:8:3] =  [1 4 7]
slicing b this way [1:2:1] gives this  ['a' 'b']
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


## Vector operations

We can apply to vectors most of the arithmetic, logical and comparison methods and these operations work on a element by element basis.

In [15]:
#sum of two vectors
vec_1 = np.array([1, 2, 3, 4, 5])
vec_2 = np.array([-1, 2, -3, 4, -5])
vec_sum = vec_1 + vec_2
print(vec_sum)

[0 4 0 8 0]


In [16]:
smaller_vec = np.array([2, 3, 4, 5])
e = ""
try:
    print(vec_1 + smaller_vec)
except Exception as e:
    print("Mismatch between dimensions of vectors used gives this error: ")
    print(e)

Mismatch between dimensions of vectors used gives this error: 
operands could not be broadcast together with shapes (5,) (4,) 


In [18]:
vec_1_multiplied = 5 * vec_1
print(f"vec_1 multiplied by a scalar quantity 5 gives {vec_1_multiplied}")

vec_1 multiplied by a scalar quantity 5 gives [ 5 10 15 20 25]


The dot product multiplies the values in two vectors element-wise and then sums the result; vector dot product requires the dimensions of the two vectors to be the same. Now I will try to implement a function which computes the dot product of two vectors of the same dimensions.

In [19]:
def dot_product(a_vector, another_vector):
    """
    Takes as input two vectors with the same dimensions (shape) and returns their dot product (a scalar)
    """
    dot_product_result = 0 #initialize the dot product result before running the for loop
    for i in range(a_vector.shape[0]):
        dot_product_result = dot_product_result + a_vector[i]*another_vector[i]
    return dot_product_result

In [21]:
dot_product_vec_1_vec_2 = dot_product(vec_1, vec_2)
print(dot_product_vec_1_vec_2)

#or equivalently

print(f"the dot product of vec_1 and vec_2 is {dot_product(vec_1, vec_2)}")

-15
the dot product of vec_1 and vec_2 is -15


In [24]:
# test np.dot routine

dot_prod_vec_1_vec_2 = np.dot(vec_1, vec_2)
print(f"NumPy 1-D np.dot(vec_1, vec_2) = {dot_prod_vec_1_vec_2}, np.dot(vec_1, vec_2).shape = {dot_prod_vec_1_vec_2.shape} ") 

#being it a vector product, it works even the other way around

dot_prod_other_way = np.dot(vec_2, vec_1)
print(f"Numpy dot product (vec_2, vec_1) gives this as result {dot_prod_other_way} and has the same shape as before {dot_prod_other_way.shape}")

NumPy 1-D np.dot(vec_1, vec_2) = -15, np.dot(vec_1, vec_2).shape = () 
Numpy dot product (vec_2, vec_1) gives this as result -15 and has the same shape as before ()


 ## np.dot vs for loop 

 Numpy np.dot routine improves efficiency as we can see from this example below:

In [32]:
#initialize a random seed
np.random.seed(1)

#define two large arrays

a_large_array = np.random.rand(1000000)
another_large_array = np.random.rand(1000000)

tic = time.time()  # capture start time
dot_product_between_two_large_arrays = np.dot(a_large_array, another_large_array)
toc = time.time()  # capture end time

print(f"the np.dot routine between the two large arrays just defined = {dot_product_between_two_large_arrays:.4f}") 
#4f here indicates the number of decimals after the comma

#lets see how much time it took to compute that
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
dot_prod_between_large_arrays_with_dot_prod_function = dot_product(a_large_array, another_large_array)
toc = time.time()  # capture end time

print(f"dot_product(a_large_array, another_large_array) =  {dot_prod_between_large_arrays_with_dot_prod_function:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a_large_array);del(another_large_array)  #remove these big arrays from memory

the np.dot routine between the two large arrays just defined = 249825.0234
Vectorized version duration: 0.0000 ms 
dot_product(a_large_array, another_large_array) =  249825.0234
loop version duration: 748.5704 ms 
